# Chapter 5 - Getting Started With Python
The following are my notes and examples from Python for Data Analytics

In [3]:
from pandas import Series, DataFrame

In [4]:
import pandas as pd

In [5]:
import numpy as np

## Series
One dimensional array-like object containing an array of data and an associated array of data labels, called its index

In [6]:
# Creating a Series from an array of data
obj = Series([4, 7, -5, 3])

In [7]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [8]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [9]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [10]:
# Creating a Series with an index identifying each data point
obj2 = Series([4, 7, -5, 3], index = ['d', 'b', 'a', 'c'])

In [11]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [12]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [13]:
obj2['a']

-5

In [14]:
obj2['d'] = 6
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [15]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [16]:
# NumPy array operations, such as filtering with a boolean array, scalar 
# mult, or math funcs, will preserve the index-value link
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [17]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [18]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [19]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [20]:
# many functions that take a dict also can use series
'b' in obj2

True

In [21]:
'e' in obj2

False

In [22]:
# You can make a Series from a dict - puts it in aphabetical order
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = Series(sdata)
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [23]:
# When passing in a dict, only info corresponding to an index is stored
# every key in the index must have a value, NaN when not found
# Utah is not in obj4, because its not in the index

states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = Series(sdata, index = states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [24]:
# isnull and notnull in pandas to detect NaN's
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [25]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [26]:
# Series also has these as instance methods
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [27]:
# automatically aligns differently indexed data in arithmetic operations
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [28]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [29]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [30]:
# both the series object and the index can have names
obj4.name = 'population'
obj4.index.name = 'state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [31]:
# a Series's index can be altered in place by assignment
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [32]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

# DataFrame

In [33]:
#constuct a dataframe from a dict of equal-length lists or np arrays
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}
frame = DataFrame(data)
frame

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [34]:
# you can specify which columns to include
DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [35]:
# as with series, if you pass a column that isn't contained in data, it will
# appear with NA values in the result
frame2 = DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                  index=['one', 'two', 'three', 'four', 'five'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [36]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [37]:
# A column in a DF can be retreived as a Series either by dict-like notation 
# or by attribute
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [38]:
# the returned Series have the same inex as the DF and their name is set 
# appropriately
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [39]:
# Rows can also be retireied position or name (such as the ix indexing field)
frame2.ix['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [40]:
# Columns can be modified by assignment
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

In [41]:
frame2['debt'] = np.arange(5.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0

In [42]:
# when setting a column to a series, it will match the indicies, and NaN for rest
val = Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [43]:
# Assigning a column that doesn't exist will create a new column.
# the del keywork will delete clumns as with a dict
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt eastern
one    2000    Ohio  1.5   NaN    True
two    2001    Ohio  1.7  -1.2    True
three  2002    Ohio  3.6   NaN    True
four   2001  Nevada  2.4  -1.5   False
five   2002  Nevada  2.9  -1.7   False

In [44]:
del frame2['eastern']
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [45]:
# you can also make data frames form nested dicts
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
         'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

frame3 = DataFrame(pop)
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [46]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [47]:
# The keys in the inner dicts won't be unioned and sorted if an explicit 
# index is specified
DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [48]:
# Dicts of Series are treated much in the same way
pdata = {'Ohio': frame3['Ohio'][:-1],
          'Nevada': frame3['Nevada'][:2]}
DataFrame(pdata)

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7

In [49]:
frame3.index.name = 'year'; frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [50]:
# returns a 2d array
frame3.values

array([[ nan,  1.5],
       [ 2.4,  1.7],
       [ 2.9,  3.6]])

In [51]:
# if Df's columns are different dtypes, dtypes of the array will accomodate
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7]], dtype=object)

## Index Objects

In [52]:
# Index objects hold axis labels and other metadata
obj = Series(range(3), index = ['a', 'b', 'c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [53]:
index[1:]

Index(['b', 'c'], dtype='object')

In [54]:
# Index objects are immutable and can't be modiifed by the user
index[1] = 'd'

TypeError: Index does not support mutable operations

In [55]:
# Immutablility means that Index objects can be shared aomg data structures
index= pd.Index(np.arange(3))
obj2 = Series([1.5, -2.5, 0], index = index)
obj2.index is index

True

In [56]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [57]:
'Ohio' in frame3.columns

True

In [58]:
2003 in frame3.index

False

# Essential Functionality 

## Reindexing
Create a new object with the data conformed to a new index 

In [59]:
obj = Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [60]:
# Calling reindex rearranges the data according to the new index,
# introducing missing values if any index calues were not already present
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [61]:
obj.reindex(['a', 'b', 'c', 'd', 'e'], fill_value=0)

a   -5.3
b    7.2
c    3.6
d    4.5
e    0.0
dtype: float64

In [62]:
# different ways to fill incldue ffill and bfill
obj3 = Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [63]:
# With Dataframe, reindex can alter rows, columns, or both
frame = DataFrame(np.arange(9).reshape((3, 3)), index=['a', 'c', 'd'], 
                 columns=['Ohio', 'Texas', 'California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [64]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [65]:
# the columns can be reindexed using the columns keyword
states = ['Texas', 'Utah', 'California']
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [66]:
# side note: columns are also dtype Index
frame.columns

Index(['Ohio', 'Texas', 'California'], dtype='object')

In [67]:
# Both can be reindexed in one shot, interpolation will only appear row-wise
frame.reindex(index=['a', 'b', 'c', 'd'],  method='ffill', columns=states)

Texas  Utah  California
a      1   NaN           2
b      1   NaN           2
c      4   NaN           5
d      7   NaN           8

## Dropping entries from an axis

In [68]:
obj = Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [69]:
# drop preserves original data
obj.drop(['b', 'c'])

a    0.0
d    3.0
e    4.0
dtype: float64

In [70]:
# with DF, index values can be deleted from either axis:
data = DataFrame(np.arange(16).reshape(4, 4),
                index=['Ohio', 'Colorado', 'Utah', 'New York'],
                columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [71]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [72]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [73]:
data.drop(['two', 'four'], axis=1)

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

## Indexing, selection, and filtering
Series indexing works the same as NumPy array indexing, except you can use the Series' index values instead of only integers

In [74]:
obj = Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [75]:
obj['b']

1.0

In [76]:
obj[1]

1.0

In [77]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [78]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [79]:
obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [80]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [82]:
# slicing behaves differently than normal - endpoints are inclusive
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [83]:
# setting using slicing works the same
obj['b':'c'] = 5
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [85]:
data = DataFrame(np.arange(16).reshape((4, 4)),
        index=['Ohio', 'Colorado', 'Utah', 'New York'],
        columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [86]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [87]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [88]:
# selecting rows of a data frame by slicing
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [89]:
# boolean indexing 
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [90]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [92]:
data[data < 5] = 0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [93]:
# The book taught using pandas.ix, but it is now deprecated,
# see this link: https://stackoverflow.com/questions/31593201/pandas-iloc-vs-ix-vs-loc-explanation

# instead, we now use loc and iloc
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [95]:
# to switch between indexing operators, use the index.get_loc() method

data.iloc[[data.index.get_loc('Colorado'), data.index.get_loc('Utah')],
          [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [96]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [97]:
data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [105]:
# Only .loc supports boolean selections,
# see: http://www.shanelynn.ie/select-pandas-dataframe-rows-and-columns-using-iloc-loc-and-ix/

# ix makes these things more concise, but loc and iloc also clarify
# it a great deal
data.loc[(data['three'] > 5), :data.columns[2]]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

## Arithmetic and data alignment

In [106]:
s1 = Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [108]:
s2 = Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [109]:
# index pairs that match will be added, 
# index pairs that don't match will be added as a NaN
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [110]:
#In the case of DataFrame, alignment is performed on both the rows and the columsn

df1 = DataFrame(np.arange(9.).reshape((3, 3)), columns = list('bcd'),
                index=['Ohio', 'Texas', 'Colorado'])
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [111]:
df2 = DataFrame(np.arange(12.).reshape((4,3)), columns = list('bde'),
               index = ['Utah', 'Ohio', 'Texas', 'Oregon'])
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [112]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

### Arithmetic Methods with Fill Values

In [113]:
df1 = DataFrame(np.arange(12.).reshape((3, 4)), columns=list('abcd'))
df2 = DataFrame(np.arange(20.).reshape((4, 5)), columns=list('abcde'))

In [114]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [115]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [116]:
# simple addition results in NA values in locations that don't overlap
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [117]:
# we can use the add method instead
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [118]:
# relatedly, when reindexing a Series of DataFrame, you can also 
# specify a fill_value
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

### Arithmetic methods with fill values

In [119]:
# In a numpy 2d array
arr = np.arange(12.).reshape((3, 4))
arr

array([[  0.,   1.,   2.,   3.],
       [  4.,   5.,   6.,   7.],
       [  8.,   9.,  10.,  11.]])

In [120]:
arr[0]

array([ 0.,  1.,  2.,  3.])

In [121]:
arr-arr[0]

array([[ 0.,  0.,  0.,  0.],
       [ 4.,  4.,  4.,  4.],
       [ 8.,  8.,  8.,  8.]])

In [122]:
# a similar operation can be done on df
frame = DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
        index=['Utah', 'Ohio', 'Texas', 'Oregon'])
series = frame.iloc[0]

In [123]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [124]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [125]:
# arithmetic matches the columns and then broadcasts down the rows
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [126]:
series2 = Series(range(3), index=['b', 'e', 'f'])
series2

b    0
e    1
f    2
dtype: int32

In [127]:
# if an index is noe found in either the df's columns or the series' index
# the objects will be reindexined to form the union
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [132]:
series3 = frame['d']
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [133]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [134]:
# broadcasting over the colunns, matching on the rows, use the arithmetic methods

frame.sub(series3, axis=0)

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

## Sorting and Ranking

In [136]:
# the sort_index method sorts lexicographically by row or column index
obj = Series(range(4), index=['d', 'a', 'b', 'c'])
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int32

In [137]:
# with a df, you can sort by index on either axis
frame = DataFrame(np.arange(8).reshape((2, 4)), index=['three', 'one'],
        columns=['d', 'a', 'b', 'c'])
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [138]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [139]:
# to sort in a descending order
frame.sort_index(axis = 1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [143]:
# to sort a Series by its values, use its sort_values method

obj = Series([4, 7, -3, 2])
obj.sort_values(ascending=False)

1    7
0    4
3    2
2   -3
dtype: int64

In [145]:
# any missing values are sorted to the end by default, no matter order
obj = Series([4, np.nan, 7, np.nan, -3, 2])
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [146]:
# on dataframe, you can sort by the values in one or more columns:
frame = DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})
frame

a  b
0  0  4
1  1  7
2  0 -3
3  1  2

In [148]:
frame.sort_values(by='b')

a  b
2  0 -3
3  1  2
0  0  4
1  1  7

In [149]:
frame.sort_values(by=['a', 'b'])

a  b
2  0 -3
0  0  4
3  1  2
1  1  7

## Axis indexes with duplicate values

In [150]:
obj = Series(range(5), index=['a', 'a', 'b', 'b', 'c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int32

In [151]:
# check if values of an index are unique or not
obj.index.is_unique

False

In [154]:
# Data selection
obj['a']

a    0
a    1
dtype: int32

In [155]:
obj['c']

4

In [156]:
# this works to index rows in a data frame as well
df = DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])
df

0         1         2
a  0.116372  0.967857  2.002847
a  1.036404 -0.419850 -1.187844
b -0.025518  2.379313  0.507697
b  0.667065  1.795526 -0.477262

In [157]:
df.loc['b']

0         1         2
b -0.025518  2.379313  0.507697
b  0.667065  1.795526 -0.477262

# Summarizing and Computing Descriptive Statistics

In [159]:
df = DataFrame([[1.4, np.nan], [7.1, -4.5],
        [np.nan, np.nan], [0.75, -1.3]],
        index=['a', 'b', 'c', 'd'],
        columns=['one', 'two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [160]:
# sum returns a series containing column sums
df.sum()

one    9.25
two   -5.80
dtype: float64

In [161]:
# passing axis=1 gets row sums instead
df.sum(axis=1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [162]:
# NA values are excluded unless the entire slice is NA. This can be disabled

df.mean(axis=1, skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [163]:
df.mean(axis=1)

a    1.400
b    1.300
c      NaN
d   -0.275
dtype: float64

In [165]:
# idxmin and idxmax give the index value where the min and max are located
df.idxmax()

one    b
two    d
dtype: object

In [168]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [166]:
# a whole lot of summary stats in one
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [167]:
# describe produces alternate stats for non-numeric data
obj = Series(['a', 'a', 'b', 'c']*4)
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

# Hierarchical Indexing

In [179]:
data = Series(np.random.randn(10),
                index=[['a', 'a', 'a', 'b', 'b', 'b', 'c', 'c', 'd', 'd'],
                [1, 2, 3, 1, 2, 3, 1, 2, 2, 3]])
data

a  1    0.357056
   2   -1.120880
   3   -0.898372
b  1    0.719695
   2    2.494190
   3    0.857876
c  1   -0.839456
   2   -0.142437
d  2   -0.904925
   3   -0.948079
dtype: float64

In [180]:
data.index

MultiIndex(levels=[['a', 'b', 'c', 'd'], [1, 2, 3]],
           labels=[[0, 0, 0, 1, 1, 1, 2, 2, 3, 3], [0, 1, 2, 0, 1, 2, 0, 1, 1, 2]])

In [181]:
data['b']

1    0.719695
2    2.494190
3    0.857876
dtype: float64

In [182]:
data['b':'c']

b  1    0.719695
   2    2.494190
   3    0.857876
c  1   -0.839456
   2   -0.142437
dtype: float64

In [183]:
data.loc[['b', 'd']]

b  1    0.719695
   2    2.494190
   3    0.857876
d  2   -0.904925
   3   -0.948079
dtype: float64

In [184]:
# Selection is even possible in some cases from an "inner" level
data[:, 2]

a   -1.120880
b    2.494190
c   -0.142437
d   -0.904925
dtype: float64

In [185]:
# This data can be rearranged into a DataFrame using its unstack method
data.unstack()

1         2         3
a  0.357056 -1.120880 -0.898372
b  0.719695  2.494190  0.857876
c -0.839456 -0.142437       NaN
d       NaN -0.904925 -0.948079

In [186]:
# The inverse operation of unstack is stack, on dataframe
data.unstack().stack()

a  1    0.357056
   2   -1.120880
   3   -0.898372
b  1    0.719695
   2    2.494190
   3    0.857876
c  1   -0.839456
   2   -0.142437
d  2   -0.904925
   3   -0.948079
dtype: float64

In [187]:
# with data frame, either axis can have a hierarchal index:
frame = DataFrame(np.arange(12).reshape((4, 3)),
                    index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
                    columns=[['Ohio', 'Ohio', 'Colorado'],
                    ['Green', 'Red', 'Green']])
frame

Ohio     Colorado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [188]:
frame.index.names = ['key1', 'key2']
frame.columns.names=['state', 'color']
frame

state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [189]:
frame.axes

[MultiIndex(levels=[['a', 'b'], [1, 2]],
            labels=[[0, 0, 1, 1], [0, 1, 0, 1]],
            names=['key1', 'key2']),
 MultiIndex(levels=[['Colorado', 'Ohio'], ['Green', 'Red']],
            labels=[[1, 1, 0], [0, 1, 0]],
            names=['state', 'color'])]

In [191]:
# with partial column indexing you can similar select groups of columns
frame['Ohio']

color      Green  Red
key1 key2            
a    1         0    1
     2         3    4
b    1         6    7
     2         9   10

## Reordering and Sorting Levels

In [193]:
frame.swaplevel('key1', 'key2')

state      Ohio     Colorado
color     Green Red    Green
key2 key1                   
1    a        0   1        2
2    a        3   4        5
1    b        6   7        8
2    b        9  10       11

In [194]:
# sortlevel stably sorts the data using only the values in a single level
frame.sortlevel(1)

state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
b    1        6   7        8
a    2        3   4        5
b    2        9  10       11

In [198]:
frame.swaplevel(0, 1).sortlevel(0)

state      Ohio     Colorado
color     Green Red    Green
key2 key1                   
1    a        0   1        2
     b        6   7        8
2    a        3   4        5
     b        9  10       11

## Summary Statistics by level

In [199]:
frame.sum(level='key2')

state  Ohio     Colorado
color Green Red    Green
key2                    
1         6   8       10
2        12  14       16

## Using a DataFrame's Columns

In [201]:
frame = DataFrame({'a': range(7), 'b': range(7, 0, -1),
                    'c': ['one', 'one', 'one', 'two', 'two', 'two', 'two'],
                    'd': [0, 1, 2, 0, 1, 2, 3]})
frame

a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

In [202]:
# the set_index function will create a new Dataframe using one or more of its columns as the index
frame2 = frame.set_index(['c', 'd'])
frame2

a  b
c   d      
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1

In [203]:
# you can also choose to leave the columns in
frame.set_index(['c', 'd'], drop=False)

a  b    c  d
c   d              
one 0  0  7  one  0
    1  1  6  one  1
    2  2  5  one  2
two 0  3  4  two  0
    1  4  3  two  1
    2  5  2  two  2
    3  6  1  two  3

In [204]:
#reset_index removes hierarchical indices and turns them into columns
frame2.reset_index()

c  d  a  b
0  one  0  0  7
1  one  1  1  6
2  one  2  2  5
3  two  0  3  4
4  two  1  4  3
5  two  2  5  2
6  two  3  6  1