# The Python Programming Language: Functions

In [6]:
x = 2
y = 3
x + y

5

In [7]:
x

2

add_numbers is a function that takes two numbers and adds them together.

In [8]:
def add_numbers(x, y):
    return x + y

add_numbers(1, 2)

3

In [9]:
def add_numbers(x, y, z=None):
    if (z == None):
        return x+y
    else:
        return x+y+z

print(add_numbers(1, 2, 3))
print(add_numbers(1, 2))

6
3


In [10]:
def add_numbers(x, y, z=None, flag=False):
    if (flag):
        print("Flag is true!")
    if (z==None):
        return x+y
    else:
        return x+y+z
print(add_numbers(1, 2, flag=True))

Flag is true!
3


In [11]:
def add_numbers(x, y):
    return x+y
a = add_numbers
a(1, 2)

3

# Types and Sequences

In [12]:
type('This is a string')

str

In [13]:
type(None)

NoneType

In [14]:
type(1)

int

In [15]:
type(1.8)

float

In [16]:
type(add_numbers)

function

Tuples are an immutable data type

In [18]:
x = (1, 'a', 2, 'b')
type(x)

tuple

Lists are a mutable data type

In [19]:
x = [1, 'a', 2, 'b']
type(x)

list

In [20]:
x.append(3.3)
print(x)

[1, 'a', 2, 'b', 3.3]


In [21]:
for item in x:
    print(item)

1
a
2
b
3.3


In [22]:
i = 0
while ( i != len(x)):
    print(x[i])
    i = i+1

1
a
2
b
3.3


In [23]:
[1, 2] + [3, 4]

[1, 2, 3, 4]

In [24]:
[1] * 3

[1, 1, 1]

In [25]:
1 in [1, 2, 3]

True

In [26]:
x = 'This is a string'
print(x[0])
print(x[0:1])
print(x[0:2])

T
T
Th


In [27]:
x[-1]

'g'

In [28]:
x[-4:-2]

'ri'

In [29]:
x[:3]

'Thi'

In [30]:
x[3:]

's is a string'

In [31]:
firstname='Christopher'
lastname='Brooks'

print(firstname + ' '+ lastname)
print(firstname * 3)
print('Chris' in firstname)

Christopher Brooks
ChristopherChristopherChristopher
True


In [32]:
firstname = 'Christopher Arthur Hansen Brooks'.split(' ')[0] # [0] selects the first element of the list
lastname = 'Christopher Arthur Hansen Brooks'.split(' ')[-1] # [-1] selects the last element of the list
print(firstname)
print(lastname)

Christopher
Brooks


In [33]:
x = {'Christopher Brooks': 'brooksch@umich.edu',
     'Bill Gates': 'billg@microsoft.com'}
x['Christopher Brooks']

'brooksch@umich.edu'

In [35]:
x['Kevyn Collins-Thompson'] = None
x['Kevyn Collins-Thompson']

In [36]:
for name in x:
    print(x[name])

brooksch@umich.edu
billg@microsoft.com
None


In [38]:
for email in x.values():
    print(email)

brooksch@umich.edu
billg@microsoft.com
None


In [40]:
for name, email in x.items():
    print(name)
    print(email)

Christopher Brooks
brooksch@umich.edu
Bill Gates
billg@microsoft.com
Kevyn Collins-Thompson
None


In [41]:
x = ('Christopher', 'Brooks', 'brooksch@umich.edu')
fname, lname, email = x

In [42]:
fname

'Christopher'

In [43]:
lname

'Brooks'

In [45]:
x = ('Christopher', 'Brooks', 'brooksch@umich.edu', 'Ann Arbor')
fname, lname, email, city = x

In [46]:
city

'Ann Arbor'

# More on Strings

In [47]:
print('Chris' + 2)

TypeError: must be str, not int

In [48]:
print('Chris' + str(2))

Chris2


In [51]:
sales_record = {
'price': 3.24,
'num_items': 4,
'person': 'Chris'
}

sales_statement = '{} bought {} item(s) at a price of {} each for a total of {}'

print(sales_statement.format(sales_record['person'],
                            sales_record['num_items'],
                            sales_record['price'],
                            sales_record['num_items']*sales_record['price']))

Chris bought 4 item(s) at a price of 3.24 each for a total of 12.96


# Reading and Writing CSV Files

In [53]:
import csv

%precision 2

with open('mpg.csv') as csvfile:
    mpg = list(csv.DictReader(csvfile))

mpg[:3]

[OrderedDict([('', '1'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'auto(l5)'),
              ('drv', 'f'),
              ('cty', '18'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '2'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'manual(m5)'),
              ('drv', 'f'),
              ('cty', '21'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '3'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '2'),
              ('year', '2008'),
              ('cyl', '4'),
              ('trans', 'manual(m6)'),
              ('drv',

In [54]:
len(mpg)

234

In [55]:
mpg[0].keys()

odict_keys(['', 'manufacturer', 'model', 'displ', 'year', 'cyl', 'trans', 'drv', 'cty', 'hwy', 'fl', 'class'])

In [56]:
sum(float(d['cty']) for d in mpg) / len(mpg)

16.86

In [58]:
sum(float(d['hwy']) for d in mpg) / len(mpg)

23.44

In [62]:
cylinders =set(d['cyl'] for d in mpg)
cylinders

{'4', '5', '6', '8'}

In [65]:
CtyMpgByCyl = []

for c in cylinders:
    summpg = 0
    cyltypecount = 0
    for d in mpg:
        if d['cyl'] == c:
            summpg += float(d['cty'])
            cyltypecount += 1
    CtyMpgByCyl.append((c, summpg/cyltypecount))

CtyMpgByCyl.sort(key = lambda x:x[0])
CtyMpgByCyl

[('4', 21.01), ('5', 20.50), ('6', 16.22), ('8', 12.57)]

In [66]:
vehicleclass = set(d['class'] for d in mpg)
vehicleclass

{'2seater', 'compact', 'midsize', 'minivan', 'pickup', 'subcompact', 'suv'}

In [69]:
HwyMpgByClass = []

for t in vehicleclass:
    summpg = 0
    classcount = 0
    for d in mpg:
        if d['class'] == t:
            summpg += float(d['hwy'])
            classcount += 1
    HwyMpgByClass.append((t, summpg/classcount))
    
HwyMpgByClass.sort(key = lambda x:x[1])
HwyMpgByClass

[('pickup', 16.88),
 ('suv', 18.13),
 ('minivan', 22.36),
 ('2seater', 24.80),
 ('midsize', 27.29),
 ('subcompact', 28.14),
 ('compact', 28.30)]

# Dates and Times

In [70]:
import datetime as dt
import time as tm

In [71]:
tm.time()

1494788541.80

In [73]:
dtnow = dt.datetime.fromtimestamp(tm.time())
dtnow

datetime.datetime(2017, 5, 14, 15, 2, 52, 573379)

In [74]:
dtnow.year, dtnow.month, dtnow.day, dtnow.hour, dtnow.minute, dtnow.second

(2017, 5, 14, 15, 2, 52)

In [75]:
delta = dt.timedelta(days = 100)
delta

datetime.timedelta(100)

In [76]:
today = dt.date.today()

In [77]:
today - delta

datetime.date(2017, 2, 3)

In [78]:
today > today-delta

True

# Objects and map()

In [79]:
class Person():
    department = 'School of Information'
    
    def set_name(self, new_name):
        self.name = new_name
    def set_location(self, new_location):
        self.location = new_location

In [81]:
person = Person()
person.set_name("Christopher Brooks")
person.set_location("Short Hills, NJ")
print('{} lives in {} and works in the department {}'.format(person.name, person.location, person.department))

Christopher Brooks lives in Short Hills, NJ and works in the department School of Information


In [82]:
store1 = [10.00, 11.00, 12.34, 2.34]
store2 = [9.00, 11.10, 12.34, 2.01]
cheapest = map(min, store1, store2)
cheapest

# Lambda and List Comprehensions

In [83]:
my_function = lambda a, b, c: a + b

In [84]:
my_function(1, 2, 3)

3

In [86]:
my_list = []
for number in range(0, 1000):
    if number % 2 == 0:
        my_list.append(number)
my_list

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

In [87]:
my_list = [number for number in range(0, 1000) if number % 2 == 0]
my_list

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

# NumPy

In [88]:
import numpy as np

## Creating Arrays

In [91]:
mylist = [1, 2, 3]
x = np.array(mylist)
x

array([1, 2, 3])

In [94]:
y = np.array([1, 2, 3])
y

array([1, 2, 3])

In [95]:
m = np.array([[7, 8, 9], [10, 11, 12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

In [96]:
m.shape

(2, 3)

In [98]:
n = np.arange(0, 30, 2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [100]:
n = n.reshape(3,5)
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [101]:
o = np.linspace(0, 4, 9)
o

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ])

In [103]:
o.resize(3, 3)
o

array([[ 0. ,  0.5,  1. ],
       [ 1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ]])

In [105]:
np.ones((3, 2))

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [106]:
np.zeros((2, 3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [107]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [108]:
np.diag(y)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [109]:
np.repeat([1, 2, 3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [110]:
np.array([1, 2, 3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [112]:
p = np.ones((2, 3), int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [113]:
np.vstack([p, 2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [114]:
np.hstack([p, 2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

# Operations

In [116]:
print(x+y) 
print(x-y)

[2 4 6]
[0 0 0]


In [117]:
x *y

array([1, 4, 9])

In [118]:
x /y

array([ 1.,  1.,  1.])

In [119]:
x**2 

array([1, 4, 9])

In [120]:
x.dot(y)

14

In [121]:
z= np.array([y, y**2])
z

array([[1, 2, 3],
       [1, 4, 9]])

In [122]:
z.shape

(2, 3)

In [123]:
z.T

array([[1, 1],
       [2, 4],
       [3, 9]])

In [124]:
z.T.shape

(3, 2)

In [125]:
z.dtype

dtype('int32')

In [127]:
z = z.astype('f') # cast to a certain type
x.dtype

dtype('int32')

In [129]:
a = np.array([-4, -2, 1, 3, 5])

In [130]:
a.sum()

3

In [131]:
a.max()

5

In [132]:
a.min()

-4

In [134]:
a.mean()

0.60

In [135]:
a.std()

3.26

In [136]:
a.argmax()

4

In [137]:
a.argmin()

0

# Indexing and Slicing

In [138]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [140]:
s[0], s[4], s[0:3]

(0, 16, array([0, 1, 4]))

In [141]:
s[1:5]

array([ 1,  4,  9, 16])

In [142]:
a[-4:]

array([-2,  1,  3,  5])

In [143]:
s[-5::-2] # start at -5 til beginning step size -2

array([64, 36, 16,  4,  0])

In [145]:
r = np.arange(36)
r.resize((6, 6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [146]:
r[2, 2]

14

In [147]:
r[3, 3:6]

array([21, 22, 23])

In [148]:
r[:2, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [149]:
r[-1, ::2]

array([30, 32, 34])

In [150]:
r[r>30]

array([31, 32, 33, 34, 35])

In [151]:
r[r>3]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35])

In [152]:
r[r>30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

# Copying Data

In [153]:
r2 = r[:3, :3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [154]:
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [155]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [156]:
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [157]:
r_copy[:] = 10
print(r_copy, '\n')
print(r)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]] 

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


## Iterating Over Arrays

In [160]:
test=  np.random.randint(0, 10, (4, 3))
test

array([[7, 4, 4],
       [2, 8, 7],
       [8, 2, 3],
       [3, 8, 4]])

In [161]:
for row in test:
    print(row)

[7 4 4]
[2 8 7]
[8 2 3]
[3 8 4]


In [162]:
for i in range(len(test)):
    print(test[i])

[7 4 4]
[2 8 7]
[8 2 3]
[3 8 4]


In [163]:
for i,row in enumerate(test):
    print('row', i, 'is', row)

row 0 is [7 4 4]
row 1 is [2 8 7]
row 2 is [8 2 3]
row 3 is [3 8 4]


In [164]:
test2 = test**2
test2

array([[49, 16, 16],
       [ 4, 64, 49],
       [64,  4,  9],
       [ 9, 64, 16]])

In [165]:
for i,j in zip(test, test2):
    print(i, '+', j, '=', i+j)

[7 4 4] + [49 16 16] = [56 20 20]
[2 8 7] + [ 4 64 49] = [ 6 72 56]
[8 2 3] + [64  4  9] = [72  6 12]
[3 8 4] + [ 9 64 16] = [12 72 20]
